version: '3.7'

services:
  backend:
    build: backend

    networks:
      - backend_network
      - frontend_network 
      
    ports: 
      - '5000:5000'

  app:
    build: app

    networks:
      - backend_network

  web:
    build: web

    ports: 
      - "3000:3000"

    networks:
      - frontend_network

    depends_on: 
      - app

networks: 
  backend_network:
  frontend_network:
